course-platform:
  serviceRegistry:
    username: serviceRegistry
    password: 'course-platform123sr'
  auth:
    jwtSecret: ${JWT_SECRET}
    jwtExpirationMs: 14400000

eureka:
  client:
    service-url:
      defaultZone: 'http://${course-platform.serviceRegistry.username}:${course-platform.serviceRegistry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost