server:
  port: 8084
  servlet:
    context-path: '/course-platform-notification/'

spring:
  application:
    name: course-platform-notification-service
  datasource:
    url: jdbc:postgresql://localhost:5432/course-platform-notification
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  output:
    ansi:
      enabled: always
  rabbitmq:
    addresses: ${RABBITMQ_ADDRESSES}


logging:
  level:
    com.victorxavier.course_platform: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO


course_platform:
  broker:
    exchange:
      notificationCommandExchange: course_platform.notificationcommand
    queue:
      notificationCommandQueue:
        name: course_platform.notificationcommand.ms.notification
    key:
      notificationCommandKey: ms.notification

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health